---
disableAuth: true

image:
  repository: ghcr.io/den-vasyliev/agentregistry-inventory
  pullPolicy: IfNotPresent
  tag: latest

httpApi:
  serviceType: ClusterIP

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
